apiVersion: apps/v1

kind: Deployment

metadata:

  name: industryappdeployment

spec:

  replicas: 2

  selector:

    matchLabels:

      type: webserver

  template:

    metadata:

      labels:

        type: webserver
    spec:

      containers:

        - name: c1

          image: nirmalendusahu/industryapp:15