apiVersion: v1
kind: Service
metadata:
  name: industryappservice
spec:
  type: NodePort
  selector:
    type: webserver
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30018